preload = /home/woeter/Pictures/Wallpapers/catppuccin-wallpaper-11.png
wallpaper = ,/home/woeter/Pictures/Wallpapers/catppuccin-wallpaper-11.png

wallpaper {
    monitor = 
    path = /home/woeter/Pictures/Wallpapers/catppuccin-wallpaper-11.png
    fit_mode = cover
}

splash = false
ipc = on
